### ISSUE TITLE
game crashed  

### ISSUE THREAD

**Issue by s4sutler100** [Elephant1214/MouseKeyInventoryFix#1]
https://mclo.gs/rBQnwVO    

[latest.log](https://github.com/Elephant1214/MouseKeyInventoryFix/files/13757222/latest.log)

you listed the wrong version  of MC   for forge.   Mc version 1.20.1.

**Comment by tlannigan** [comment]
I think specifically the Forge/FML version range has to be updated to be compatible with 1.20.1. This error appeared in the OP's log:

`net.minecraftforge.fml.ModLoadingException: Mod File MouseKeyInventoryFix-Forge-1.0.0.jar needs language provider javafml:between 37 and 43, (inclusive) to load
We have found 47`

And crashed the 1.20.1 Minecraft client.

**Comment by Elephant1214** [comment]
Oh right, I forgot about that. I'll update the toml sometime soon. Obfuscated mappings for the mixed function still haven't changed iirc, so that should be the only issue.
